query ListTasks {
  allTasksList(filter: { deleted: { equalTo: false } }, orderBy: NAME_ASC) {
    id
    name
    seq
    deleted
    updated
  }
}

subscription SubscribeTasks {
  taskUpdated {
    event
    task {
      id
      name
    }
  }
}